import test from'node:test';import assert from'node:assert/strict';import{createRoute}from'../lib/route-service.js';
import{buildGraph}from'../lib/routing.js';
import{cacheGet,cacheSet,clearMemoryCache,cacheStatus}from'../lib/cache.js';import{checkRateLimit}from'../lib/rate-limit.js';
import{parseRunningPlaces,runningPlacesQuery}from'../lib/overpass.js';

function fixture(lat=-34.593,lon=-58.38){const elements=[],ids=[],size=17,step=.001;for(let y=0;y<size;y++){ids[y]=[];for(let x=0;x<size;x++){const id=10000+y*size+x,p={type:'node',id,lat:lat+(y-8)*step,lon:lon+(x-8)*step};ids[y][x]=id;elements.push(p);}}let wayId=20000;for(let y=0;y<size;y++)elements.push({type:'way',id:wayId++,nodes:ids[y],geometry:ids[y].map(id=>{const p=elements[id-10000];return{lat:p.lat,lon:p.lon};}),tags:{highway:y%4===0?'tertiary':'residential',sidewalk:'yes'}});for(let x=0;x<size;x++){const col=ids.map(row=>row[x]);elements.push({type:'way',id:wayId++,nodes:col,geometry:col.map(id=>{const p=elements[id-10000];return{lat:p.lat,lon:p.lon};}),tags:{highway:x%3===0?'footway':'residential'}});}for(const[y,x]of[[8,8],[4,8],[12,8]])elements[ids[y][x]-10000].tags={crossing:'marked'};const park=[ids[5][5],ids[5][11],ids[11][11],ids[11][5],ids[5][5]];elements.push({type:'way',id:wayId++,nodes:park,geometry:park.map(id=>{const p=elements[id-10000];return{lat:p.lat,lon:p.lon};}),tags:{leisure:'park'}});return elements;}

const loadMapData=async()=>({elements:fixture(),source:'test fixture'});

for(const preset of['balanced','nature','nostops','scenic'])test(`${preset} produces a closed three-mile loop`,async()=>{const result=await createRoute({latitude:-34.593,longitude:-58.38,distanceMiles:3,preset},{loadMapData});assert.ok(result.coordinates.length>3);assert.deepEqual(result.coordinates[0],result.coordinates.at(-1));assert.ok(Math.abs(result.distanceMiles-3)/3<=.2);assert.ok(result.stats.repeatedPercent<=20);assert.equal(result.meta.mapSource,'test fixture');});

test('rejects invalid client input before loading map data',async()=>{let called=false;await assert.rejects(()=>createRoute({latitude:200,longitude:0,distanceMiles:3,preset:'balanced'},{loadMapData:async()=>{called=true;}}),/Valid latitude/);assert.equal(called,false);});

test('persistent cache survives clearing server memory',async()=>{const key=`test-${Date.now()}-${Math.random()}`,value={elements:[{id:42}]};await cacheSet(key,value);clearMemoryCache();const hit=await cacheGet(key);assert.deepEqual(hit.value,value);assert.equal(hit.source,'persistent disk cache');});

test('cache status reports fresh and stale windows without exposing credentials',()=>{const status=cacheStatus();assert.equal(status.persistentBackend,'local-disk');assert.equal(status.ttlDays,7);assert.equal(status.staleFallbackDays,30);assert.deepEqual(Object.keys(status).sort(),['memoryEntries','persistentBackend','staleFallbackDays','ttlDays']);});

test('rate limiter permits a burst then blocks excess requests',()=>{const identity=`test-${Math.random()}`;for(let i=0;i<20;i++)assert.equal(checkRateLimit(identity).allowed,true);const blocked=checkRateLimit(identity);assert.equal(blocked.allowed,false);assert.ok(blocked.retryAfter>0);});

test('presets produce the intended relative behavior',async()=>{const base={latitude:-34.593,longitude:-58.38,distanceMiles:3},[balanced,nature,noStops,scenic]=await Promise.all(['balanced','nature','nostops','scenic'].map(preset=>createRoute({...base,preset},{loadMapData})));assert.ok(nature.stats.greenPercent>=balanced.stats.greenPercent);assert.ok(scenic.stats.greenPercent>=balanced.stats.greenPercent);assert.ok(noStops.stats.crossings<=balanced.stats.crossings);for(const route of[balanced,nature,noStops,scenic])assert.ok(route.meta.targetErrorPercent<=15);});

test('one-way route finishes somewhere new',async()=>{const route=await createRoute({latitude:-34.593,longitude:-58.38,distanceMiles:1,preset:'balanced',shape:'oneway',direction:'east'},{loadMapData});assert.equal(route.meta.returnsToStart,false);assert.notDeepEqual(route.coordinates[0],route.coordinates.at(-1));assert.ok(route.meta.targetErrorPercent<=15);});

test('out-and-back route reverses to its start',async()=>{const route=await createRoute({latitude:-34.593,longitude:-58.38,distanceMiles:1,preset:'balanced',shape:'outback',direction:'north'},{loadMapData});assert.equal(route.meta.returnsToStart,true);assert.deepEqual(route.coordinates[0],route.coordinates.at(-1));assert.ok(route.stats.repeatedPercent>=45);assert.ok(route.meta.targetErrorPercent<=15);});

test('park laps repeat a closed green circuit and return home once',async()=>{const route=await createRoute({latitude:-34.593,longitude:-58.38,distanceMiles:3,preset:'nature',shape:'park',returnToStart:true},{loadMapData});assert.equal(route.meta.returnsToStart,true);assert.deepEqual(route.coordinates[0],route.coordinates.at(-1));assert.ok(route.stats.greenPercent>=85);assert.ok(route.stats.lapCount>=2);assert.ok(route.meta.targetErrorPercent<=15);});

test('park laps expose intentional lap count instead of generic route repetition',async()=>{const route=await createRoute({latitude:-34.593,longitude:-58.38,distanceMiles:3,preset:'balanced',shape:'park',returnToStart:false},{loadMapData});assert.equal(route.meta.returnsToStart,false);assert.ok(Number.isInteger(route.stats.lapCount));assert.ok(route.stats.lapCount>=2);assert.ok(route.alternatives.every(option=>option.stats.lapCount>=1));});

test('nature routes require the feature layer instead of silently using roads only',async()=>{let options;await createRoute({latitude:-34.593,longitude:-58.38,distanceMiles:1,preset:'nature',shape:'oneway'},{loadMapData:async(box,value)=>{options=value;return{elements:fixture(),source:'test fixture'};}});assert.equal(options.requireFeatures,true);});

test('park relations mark roads inside them as green',()=>{const elements=fixture(),outer=[[{lat:-34.600,lon:-58.387},{lat:-34.600,lon:-58.373},{lat:-34.586,lon:-58.373},{lat:-34.586,lon:-58.387},{lat:-34.600,lon:-58.387}]];elements.push({type:'relation',id:99999,tags:{leisure:'park'},members:outer.map(geometry=>({type:'way',role:'outer',geometry}))});const graph=buildGraph(elements);const greenEdges=[...graph.adj.values()].flat().filter(edge=>edge.green);assert.ok(greenEdges.length>0);});

test('open relation fragments are not treated as giant park polygons',()=>{const elements=[{type:'node',id:1,lat:0,lon:0},{type:'node',id:2,lat:0,lon:.001},{type:'way',id:3,nodes:[1,2],geometry:[{lat:0,lon:0},{lat:0,lon:.001}],tags:{highway:'residential'}},{type:'relation',id:4,tags:{leisure:'park'},members:[{type:'way',role:'outer',geometry:[{lat:-1,lon:-1},{lat:1,lon:-1},{lat:1,lon:1}]}]}];const graph=buildGraph(elements);assert.equal([...graph.adj.values()].flat().some(edge=>edge.green),false);});

test('routing emits real progress and candidate events',async()=>{const events=[];await createRoute({latitude:-34.593,longitude:-58.38,distanceMiles:1,preset:'balanced',shape:'oneway'},{loadMapData,onProgress:event=>events.push(event)});assert.deepEqual(events.slice(0,3).map(event=>event.stage),['loading-map','building-network','network-ready']);assert.ok(events.some(event=>event.stage==='candidate'&&event.candidate.coordinates.length>1));assert.equal(events.at(-1).stage,'complete');});

test('nearby running places are ranked, enriched, and safely filtered',()=>{const places=parseRunningPlaces([{type:'way',id:1,center:{lat:-34.593,lon:-58.379},tags:{name:'Great Park',leisure:'park',opening_hours:'06:00-22:00',wikimedia_commons:'File:Great Park.jpg',website:'https://example.com'}},{type:'way',id:2,center:{lat:-34.594,lon:-58.38},tags:{name:'Private Garden',leisure:'garden',access:'private'}},{type:'way',id:3,center:{lat:-34.7,lon:-58.38},tags:{name:'Too Far',leisure:'park'}}],{lat:-34.593,lon:-58.38},8047);assert.equal(places.length,1);assert.equal(places[0].name,'Great Park');assert.equal(places[0].openingHours,'06:00-22:00');assert.equal(places[0].detailsUrl,'https://example.com');assert.match(places[0].photoUrl,/commons\.wikimedia\.org\/wiki\/Special:Redirect\/file\/Great%20Park\.jpg/)});

test('nearby GPS readings share a cached place query',()=>{const first=runningPlacesQuery({lat:-34.5931,lon:-58.3801},2414),second=runningPlacesQuery({lat:-34.5934,lon:-58.3797},2414);assert.equal(first.query,second.query);assert.match(first.query,/around:2914/);assert.match(first.query,/out center qt 40/)});
