import{cacheGet,cacheSet}from'./cache.js';
const ENDPOINTS=['https://overpass-api.de/api/interpreter','https://overpass.private.coffee/api/interpreter','https://maps.mail.ru/osm/tools/overpass/api/interpreter'],pending=new Map();
const hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(36);};

async function request(query,timeout=25000){return new Promise((resolve,reject)=>{const controllers=[],failures=[];let finished=0,settled=false;ENDPOINTS.forEach((endpoint,i)=>setTimeout(async()=>{if(settled)return;const controller=new AbortController();controllers.push(controller);const timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetch(endpoint,{method:'POST',headers:{Accept:'application/json','Accept-Encoding':'gzip, deflate','User-Agent':'activ-route-generator/0.2'},body:new URLSearchParams({data:query}),signal:controller.signal});if(!response.ok)throw new Error(`HTTP ${response.status}`);const json=await response.json();if(!json.elements)throw new Error('invalid response');if(!settled){settled=true;controllers.forEach(c=>c!==controller&&c.abort());resolve(json);}}catch(err){failures[i]=err.name==='AbortError'?'timed out':err.message;finished++;if(finished===ENDPOINTS.length&&!settled){const error=new Error(`Map services unavailable (${failures.join('; ')})`);error.code='MAP_UNAVAILABLE';reject(error);}}finally{clearTimeout(timer);}},i*1200));});}
async function cached(query,timeout){const key=hash(query),hit=await cacheGet(key);if(hit)return{json:hit.value,source:hit.source};if(pending.has(key))return pending.get(key);const work=(async()=>{const json=await request(query,timeout);await cacheSet(key,json);return{json,source:'live Overpass'};})();pending.set(key,work);try{return await work;}finally{pending.delete(key);}}

export async function loadMapData(box,{requireFeatures=false}={}){const b=`${box.s},${box.w},${box.n},${box.e}`,roads=`[out:json][timeout:22];way[highway~"^(footway|path|residential|living_street|pedestrian|tertiary|secondary|unclassified|service|track|steps)$"][foot!="no"][access!="private"](${b});out geom;`,features=`[out:json][timeout:16];(nwr[leisure~"^(park|garden)$"](${b});nwr[landuse="forest"](${b});nwr[natural="water"](${b});nwr[waterway~"^(river|stream|canal)$"](${b});node[highway="traffic_signals"](${b});node[crossing](${b}););out geom;`;
  const featurePromise=cached(features,18000),roadResult=await cached(roads,25000);let featureResult=null;
  try{featureResult=requireFeatures?await featurePromise:await Promise.race([featurePromise,new Promise(r=>setTimeout(()=>r(null),5000))]);}catch(error){if(requireFeatures){error.code='FEATURE_DATA_UNAVAILABLE';throw error;}}
  return{elements:roadResult.json.elements.concat(featureResult?.json.elements||[]),featuresLoaded:Boolean(featureResult),source:featureResult?.source==='server memory cache'&&roadResult.source==='server memory cache'?'server memory cache':roadResult.source};}

const distanceMeters=(a,b)=>{const R=6371000,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lon-a.lon)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(x));};
const placeKind=tags=>tags.leisure==='nature_reserve'||tags.boundary==='protected_area'?'Nature reserve':tags.natural==='beach'?'Waterfront':tags.natural==='wood'||tags.landuse==='forest'?'Woodland':tags.leisure==='garden'?'Garden':'Park';
const placePhoto=tags=>{const value=tags.wikimedia_commons;if(value?.startsWith('File:'))return`https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(value.slice(5))}?width=720`;return null;};
const placeLink=tags=>{if(/^https:\/\//.test(tags.website||''))return tags.website;if(/^https:\/\//.test(tags['contact:website']||''))return tags['contact:website'];if(tags.wikipedia){const split=tags.wikipedia.indexOf(':');if(split>0)return`https://${tags.wikipedia.slice(0,split)}.wikipedia.org/wiki/${encodeURIComponent(tags.wikipedia.slice(split+1).replaceAll(' ','_'))}`;}if(tags.wikidata)return`https://www.wikidata.org/wiki/${encodeURIComponent(tags.wikidata)}`;return null;};

export function parseRunningPlaces(elements,origin,radiusMeters){const seen=new Set(),places=[];for(const element of elements){const tags=element.tags||{},lat=element.lat??element.center?.lat,lon=element.lon??element.center?.lon,name=tags.name||tags['name:en'];if(!name||!Number.isFinite(lat)||!Number.isFinite(lon)||['private','no'].includes(tags.access))continue;const distance=distanceMeters(origin,{lat,lon});if(distance>radiusMeters*1.03)continue;const key=`${name.toLowerCase()}-${Math.round(lat*1000)}-${Math.round(lon*1000)}`;if(seen.has(key))continue;seen.add(key);const kind=placeKind(tags),metadata=[tags.opening_hours,tags.surface,tags.lit,tags.website||tags['contact:website'],tags.wikimedia_commons||tags.wikidata].filter(Boolean).length,kindScore={Park:8,'Nature reserve':10,Waterfront:9,Woodland:8,Garden:6}[kind]||5,score=kindScore+metadata*.35-Math.min(5,distance/1609.344)*.42;places.push({id:`${element.type}-${element.id}`,name,kind,lat,lon,distanceMiles:Number((distance/1609.344).toFixed(1)),score:Number(score.toFixed(2)),reason:kind==='Waterfront'?'Open views and waterside running':kind==='Nature reserve'?'A larger natural area worth exploring':kind==='Garden'?'Landscaped paths close to you':`${kind} paths that can anchor your run`,openingHours:tags.opening_hours||null,access:tags.access||'public',surface:tags.surface||null,lit:tags.lit||null,photoUrl:placePhoto(tags),detailsUrl:placeLink(tags),photoAttribution:tags.wikimedia_commons?'Wikimedia Commons':null});}return places.sort((a,b)=>b.score-a.score||a.distanceMiles-b.distanceMiles);}

export async function loadRunningPlaces(origin,radiusMeters=8047){const radius=Math.max(500,Math.min(8047,Math.round(radiusMeters))),query=`[out:json][timeout:14];(wr[leisure~"^(park|garden|nature_reserve)$"][name](around:${radius},${origin.lat},${origin.lon});wr[boundary="protected_area"][name](around:${radius},${origin.lat},${origin.lon});wr[natural~"^(beach|wood)$"][name](around:${radius},${origin.lat},${origin.lon});wr[landuse="forest"][name](around:${radius},${origin.lat},${origin.lon}););out center qt 150;`,result=await cached(query,18000);return{places:parseRunningPlaces(result.json.elements,origin,radius),source:result.source,radiusMeters:radius};}
