const ENDPOINTS=['https://lz4.overpass-api.de/api/interpreter','https://z.overpass-api.de/api/interpreter','https://overpass.private.coffee/api/interpreter'];
const cache=new Map(),TTL=7*24*60*60*1000;
const hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(36);};

async function request(query,timeout=25000){return new Promise((resolve,reject)=>{const controllers=[],failures=[];let finished=0,settled=false;ENDPOINTS.forEach((endpoint,i)=>setTimeout(async()=>{if(settled)return;const controller=new AbortController();controllers.push(controller);const timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'data='+encodeURIComponent(query),signal:controller.signal});if(!response.ok)throw new Error(`HTTP ${response.status}`);const json=await response.json();if(!json.elements)throw new Error('invalid response');if(!settled){settled=true;controllers.forEach(c=>c!==controller&&c.abort());resolve(json);}}catch(err){failures[i]=err.name==='AbortError'?'timed out':err.message;finished++;if(finished===ENDPOINTS.length&&!settled)reject(new Error(`Map services unavailable (${failures.join('; ')})`));}finally{clearTimeout(timer);}},i*1200));});}
async function cached(query,timeout){const key=hash(query),hit=cache.get(key);if(hit&&Date.now()-hit.ts<TTL)return{json:hit.json,source:'memory cache'};const json=await request(query,timeout);cache.set(key,{ts:Date.now(),json});if(cache.size>8)cache.delete(cache.keys().next().value);return{json,source:'live Overpass'};}

export async function loadMapData(box){const b=`${box.s},${box.w},${box.n},${box.e}`,roads=`[out:json][timeout:22];way[highway~"^(footway|path|residential|living_street|pedestrian|tertiary|secondary|unclassified|service|track|steps)$"][foot!="no"][access!="private"](${b});out geom;`,features=`[out:json][timeout:12];(way[leisure~"^(park|garden)$"](${b});way[landuse="forest"](${b});way[natural="water"](${b});way[waterway~"^(river|stream|canal)$"](${b});node[highway="traffic_signals"](${b});node[crossing](${b}););out geom;`;
  const featurePromise=cached(features,12000).catch(()=>null),roadResult=await cached(roads,25000),featureResult=await Promise.race([featurePromise,new Promise(r=>setTimeout(()=>r(null),2500))]);return{elements:roadResult.json.elements.concat(featureResult?.json.elements||[]),source:featureResult?.source==='memory cache'&&roadResult.source==='memory cache'?'memory cache':roadResult.source};}
