export const M_PER_MI = 1609.344;

const haversine=(a,b)=>{const R=6371000,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lon-a.lon)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(x));};
const destination=(o,m,b)=>{const R=6371000,d=m/R,t=b*Math.PI/180,p1=o.lat*Math.PI/180,l1=o.lon*Math.PI/180,p2=Math.asin(Math.sin(p1)*Math.cos(d)+Math.cos(p1)*Math.sin(d)*Math.cos(t)),l2=l1+Math.atan2(Math.sin(t)*Math.sin(d)*Math.cos(p1),Math.cos(d)-Math.sin(p1)*Math.sin(p2));return{lat:p2*180/Math.PI,lon:l2*180/Math.PI};};
const pointInPolygon=(p,poly)=>{let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if(((a.lat>p.lat)!==(b.lat>p.lat))&&(p.lon<(b.lon-a.lon)*(p.lat-a.lat)/(b.lat-a.lat)+a.lon))inside=!inside;}return inside;};
const pointSegmentDistance=(p,a,b)=>{const lat0=p.lat*Math.PI/180,x=q=>(q.lon-p.lon)*111320*Math.cos(lat0),y=q=>(q.lat-p.lat)*111320,ax=x(a),ay=y(a),bx=x(b),by=y(b),dx=bx-ax,dy=by-ay,t=Math.max(0,Math.min(1,-(ax*dx+ay*dy)/(dx*dx+dy*dy||1)));return Math.hypot(ax+t*dx,ay+t*dy);};
const featureNear=(p,pts,buffer)=>{if(pts.length<2)return false;if(pts.length>2&&pointInPolygon(p,pts))return true;for(let i=1;i<pts.length;i++)if(pointSegmentDistance(p,pts[i-1],pts[i])<buffer)return true;return false;};

export function buildGraph(elements){
  const allNodes=new Map(),roadWays=[],areas=[],crossings=[];
  for(const el of elements)if(el.type==='node'&&el.lat!=null)allNodes.set(el.id,{id:el.id,lat:el.lat,lon:el.lon,ele:Number(el.tags?.ele)});
  for(const el of elements)if(el.type==='way'&&el.nodes&&el.geometry)for(let i=0;i<el.nodes.length;i++){const p=el.geometry[i];if(p&&!allNodes.has(el.nodes[i]))allNodes.set(el.nodes[i],{id:el.nodes[i],lat:p.lat,lon:p.lon,ele:NaN});}
  for(const el of elements){if(el.type==='node'&&el.tags&&(el.tags.crossing||el.tags.highway==='traffic_signals'))crossings.push(allNodes.get(el.id));if(el.type!=='way'||!el.nodes)continue;const t=el.tags||{};if(t.highway)roadWays.push(el);else if(t.leisure||t.landuse==='forest'||t.natural==='water'||t.waterway)areas.push({kind:(t.natural==='water'||t.waterway)?'water':'green',points:el.nodes.map(id=>allNodes.get(id)).filter(Boolean)});}
  const nodes=new Map(),adj=new Map(),crossGrid=new Map(),cell=.001;
  for(const c of crossings)if(c){const k=`${Math.floor(c.lat/cell)},${Math.floor(c.lon/cell)}`;(crossGrid.get(k)||crossGrid.set(k,[]).get(k)).push(c);}
  const indexedAreas=areas.filter(a=>a.points.length).map(a=>({...a,minLat:Math.min(...a.points.map(p=>p.lat)),maxLat:Math.max(...a.points.map(p=>p.lat)),minLon:Math.min(...a.points.map(p=>p.lon)),maxLon:Math.max(...a.points.map(p=>p.lon))}));
  const add=(a,b,meta)=>{if(!adj.has(a.id))adj.set(a.id,[]);adj.get(a.id).push({to:b.id,...meta});};
  for(const way of roadWays)for(let i=1;i<way.nodes.length;i++){const a=allNodes.get(way.nodes[i-1]),b=allNodes.get(way.nodes[i]);if(!a||!b)continue;nodes.set(a.id,a);nodes.set(b.id,b);const distance=haversine(a,b),key=a.id<b.id?`${a.id}-${b.id}`:`${b.id}-${a.id}`,mid={lat:(a.lat+b.lat)/2,lon:(a.lon+b.lon)/2},cy=Math.floor(mid.lat/cell),cx=Math.floor(mid.lon/cell);let near=[];for(let y=cy-1;y<=cy+1;y++)for(let x=cx-1;x<=cx+1;x++)near.push(...(crossGrid.get(`${y},${x}`)||[]));const crossingIds=near.filter(c=>haversine(mid,c)<35).map(c=>c.id);let green=false,water=false;for(const area of indexedAreas){const pad=.0005;if(mid.lat<area.minLat-pad||mid.lat>area.maxLat+pad||mid.lon<area.minLon-pad||mid.lon>area.maxLon+pad)continue;if(featureNear(mid,area.points,area.kind==='water'?45:25)){if(area.kind==='water')water=true;else green=true;}}const tags=way.tags||{},climb=Number.isFinite(a.ele)&&Number.isFinite(b.ele)?Math.abs(a.ele-b.ele):0,meta={distance,key,nearCross:crossingIds.length>0,crossingIds,green,water,climb,highway:tags.highway,surface:tags.surface||'',sidewalk:tags.sidewalk||''};add(a,b,meta);add(b,a,meta);}
  return{nodes,adj};
}

const nearestNode=(g,p)=>{let best=null,bd=Infinity;for(const n of g.nodes.values()){const d=haversine(p,n);if(d<bd){bd=d;best=n;}}return best;};
const edgeCost=(e,preset,reused)=>{let f=1;if(e.highway==='secondary')f*=e.sidewalk&&e.sidewalk!=='no'?1.55:2.8;else if(e.highway==='tertiary')f*=e.sidewalk&&e.sidewalk!=='no'?1.15:1.5;else if(e.highway==='service')f*=1.12;else if(e.highway==='steps')f*=1.65;if(['footway','path','pedestrian','living_street'].includes(e.highway))f*=.88;if(['cobblestone','sett'].includes(e.surface))f*=1.2;if(e.nearCross)f*=preset==='nostops'?10:1.12;if(preset==='nature'){if(e.green)f*=.36;if(['path','footway'].includes(e.highway))f*=.74;}if(preset==='scenic'){if(e.green)f*=.5;if(e.water)f*=.42;if(e.climb>1)f*=.86;if(['path','footway'].includes(e.highway))f*=.82;}if(preset==='balanced'&&e.green)f*=.88;if(reused)f*=12;return Math.max(e.distance*.2,e.distance*f);};
class MinHeap{constructor(){this.a=[];}get size(){return this.a.length;}push(x){let i=this.a.push(x)-1;while(i){let p=(i-1)>>1;if(this.a[p][0]<=x[0])break;this.a[i]=this.a[p];i=p;}this.a[i]=x;}pop(){const root=this.a[0],last=this.a.pop();if(this.a.length){let i=0;this.a[0]=last;while(true){let l=i*2+1,r=l+1,s=i;if(l<this.a.length&&this.a[l][0]<this.a[s][0])s=l;if(r<this.a.length&&this.a[r][0]<this.a[s][0])s=r;if(s===i)break;[this.a[i],this.a[s]]=[this.a[s],this.a[i]];i=s;}}return root;}}
function dijkstra(g,start,goal,preset,used){const dist=new Map([[start,0]]),prev=new Map(),heap=new MinHeap();heap.push([0,start]);while(heap.size){const[cost,id]=heap.pop();if(cost!==dist.get(id))continue;if(id===goal)break;for(const e of g.adj.get(id)||[]){const nc=cost+edgeCost(e,preset,used.has(e.key));if(nc<(dist.get(e.to)??Infinity)){dist.set(e.to,nc);prev.set(e.to,{id,edge:e});heap.push([nc,e.to]);}}}if(!prev.has(goal))return null;const ids=[goal],edges=[];let cur=goal,actual=0;while(cur!==start){const p=prev.get(cur);if(!p)return null;actual+=p.edge.distance;edges.push(p.edge);cur=p.id;ids.push(cur);}return{ids:ids.reverse(),distance:actual,edges:edges.reverse()};}
function candidate(g,origin,start,target,radius,rotation,preset){const points=[start];for(let i=0;i<4;i++)points.push(nearestNode(g,destination(origin,radius,rotation+i*90)));points.push(start);const used=new Set(),ids=[],edges=[];let total=0,repeatedMeters=0;for(let i=1;i<points.length;i++){if(!points[i-1]||!points[i]||points[i-1].id===points[i].id)continue;const path=dijkstra(g,points[i-1].id,points[i].id,preset,used);if(!path)return null;if(ids.length)path.ids.shift();ids.push(...path.ids);total+=path.distance;for(const e of path.edges){if(used.has(e.key))repeatedMeters+=e.distance;used.add(e.key);edges.push(e);}}if(ids.length<3||!total)return null;const greenMeters=edges.reduce((s,e)=>s+(e.green?e.distance:0),0),waterMeters=edges.reduce((s,e)=>s+(e.water?e.distance:0),0),crossings=new Set(edges.flatMap(e=>e.crossingIds||[])).size,error=Math.abs(total-target)/target,repeat=repeatedMeters/total,green=greenMeters/total,water=waterMeters/total,crossingsPerKm=crossings/(total/1000);let score=error*6+Math.max(0,error-.15)*25+repeat*5;if(preset==='balanced')score-=green*.25;if(preset==='nature')score-=green*2.4;if(preset==='scenic')score-=green*1.7+water*2;if(preset==='nostops')score+=crossingsPerKm*.14;return{coordinates:ids.map(id=>[g.nodes.get(id).lat,g.nodes.get(id).lon]),distanceMeters:total,score,stats:{greenMeters,waterMeters,crossings,repeatedMeters}};}

export function findLoop(graph,origin,target,preset){const start=nearestNode(graph,origin);if(!start)return null;let radius=target/(2*Math.PI),best=null;for(let attempt=0;attempt<3;attempt++){let ringBest=null;for(const rotation of[0,22,44,66,88,110,132,154]){const c=candidate(graph,origin,start,target,radius,rotation+attempt*7,preset);if(c&&(!ringBest||c.score<ringBest.score))ringBest=c;if(c&&(!best||c.score<best.score))best=c;}if(ringBest){const error=Math.abs(ringBest.distanceMeters-target)/target,repeat=ringBest.stats.repeatedMeters/ringBest.distanceMeters;if(error<=.1&&repeat<=.14)break;radius*=Math.max(.7,Math.min(1.38,target/ringBest.distanceMeters));}else radius*=.78;}return best;}

export function bboxFor(origin,target){const radius=Math.max(700,target/(2*Math.PI)*1.12),dLat=radius/111320,dLon=radius/(111320*Math.max(.2,Math.cos(origin.lat*Math.PI/180))),q=value=>Number(value.toFixed(3));return{s:q(origin.lat-dLat),w:q(origin.lon-dLon),n:q(origin.lat+dLat),e:q(origin.lon+dLon)};}
