export const M_PER_MI = 1609.344;

const haversine=(a,b)=>{const R=6371000,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lon-a.lon)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(x));};
const destination=(o,m,b)=>{const R=6371000,d=m/R,t=b*Math.PI/180,p1=o.lat*Math.PI/180,l1=o.lon*Math.PI/180,p2=Math.asin(Math.sin(p1)*Math.cos(d)+Math.cos(p1)*Math.sin(d)*Math.cos(t)),l2=l1+Math.atan2(Math.sin(t)*Math.sin(d)*Math.cos(p1),Math.cos(d)-Math.sin(p1)*Math.sin(p2));return{lat:p2*180/Math.PI,lon:l2*180/Math.PI};};
const pointInPolygon=(p,poly)=>{let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if(((a.lat>p.lat)!==(b.lat>p.lat))&&(p.lon<(b.lon-a.lon)*(p.lat-a.lat)/(b.lat-a.lat)+a.lon))inside=!inside;}return inside;};
const pointSegmentDistance=(p,a,b)=>{const lat0=p.lat*Math.PI/180,x=q=>(q.lon-p.lon)*111320*Math.cos(lat0),y=q=>(q.lat-p.lat)*111320,ax=x(a),ay=y(a),bx=x(b),by=y(b),dx=bx-ax,dy=by-ay,t=Math.max(0,Math.min(1,-(ax*dx+ay*dy)/(dx*dx+dy*dy||1)));return Math.hypot(ax+t*dx,ay+t*dy);};
const samePoint=(a,b)=>a&&b&&Math.abs(a.lat-b.lat)<1e-7&&Math.abs(a.lon-b.lon)<1e-7;
const featureNear=(p,pts,buffer,polygon=false)=>{if(pts.length<2)return false;if(polygon&&pts.length>3&&pointInPolygon(p,pts))return true;for(let i=1;i<pts.length;i++)if(pointSegmentDistance(p,pts[i-1],pts[i])<buffer)return true;return false;};
const relationRings=members=>{const segments=members.filter(m=>m.role!=='inner'&&m.geometry?.length>1).map(m=>m.geometry.map(p=>({lat:p.lat,lon:p.lon}))),rings=[];while(segments.length){let ring=segments.pop(),changed=true;while(changed&&!samePoint(ring[0],ring.at(-1))){changed=false;for(let i=0;i<segments.length;i++){const segment=segments[i];if(samePoint(ring.at(-1),segment[0]))ring.push(...segment.slice(1));else if(samePoint(ring.at(-1),segment.at(-1)))ring.push(...segment.slice(0,-1).reverse());else if(samePoint(ring[0],segment.at(-1)))ring.unshift(...segment.slice(0,-1));else if(samePoint(ring[0],segment[0]))ring.unshift(...segment.slice(1).reverse());else continue;segments.splice(i,1);changed=true;break;}}rings.push({points:ring,polygon:samePoint(ring[0],ring.at(-1))});}return rings;};

export function buildGraph(elements){
  const allNodes=new Map(),roadWays=[],areas=[],crossings=[];
  for(const el of elements)if(el.type==='node'&&el.lat!=null)allNodes.set(el.id,{id:el.id,lat:el.lat,lon:el.lon,ele:Number(el.tags?.ele)});
  for(const el of elements)if(el.type==='way'&&el.nodes&&el.geometry)for(let i=0;i<el.nodes.length;i++){const p=el.geometry[i];if(p&&!allNodes.has(el.nodes[i]))allNodes.set(el.nodes[i],{id:el.nodes[i],lat:p.lat,lon:p.lon,ele:NaN});}
  for(const el of elements){
    if(el.type==='node'&&el.tags&&(el.tags.crossing||el.tags.highway==='traffic_signals'))crossings.push(allNodes.get(el.id));
    const t=el.tags||{},kind=(t.natural==='water'||t.waterway)?'water':'green',isFeature=t.leisure||t.landuse==='forest'||t.natural==='water'||t.waterway;
    if(el.type==='way'&&el.nodes){if(t.highway)roadWays.push(el);else if(isFeature){const points=el.geometry?.map(p=>({lat:p.lat,lon:p.lon}))||el.nodes.map(id=>allNodes.get(id)).filter(Boolean);areas.push({kind,points,polygon:samePoint(points[0],points.at(-1))});}}
    if(el.type==='relation'&&isFeature)for(const ring of relationRings(el.members||[]))areas.push({kind,...ring});
  }
  const nodes=new Map(),adj=new Map(),crossGrid=new Map(),cell=.001;
  for(const c of crossings)if(c){const k=`${Math.floor(c.lat/cell)},${Math.floor(c.lon/cell)}`;(crossGrid.get(k)||crossGrid.set(k,[]).get(k)).push(c);}
  const indexedAreas=areas.filter(a=>a.points.length).map(a=>({...a,minLat:Math.min(...a.points.map(p=>p.lat)),maxLat:Math.max(...a.points.map(p=>p.lat)),minLon:Math.min(...a.points.map(p=>p.lon)),maxLon:Math.max(...a.points.map(p=>p.lon))}));
  const add=(a,b,meta)=>{if(!adj.has(a.id))adj.set(a.id,[]);adj.get(a.id).push({to:b.id,...meta});};
  for(const way of roadWays)for(let i=1;i<way.nodes.length;i++){const a=allNodes.get(way.nodes[i-1]),b=allNodes.get(way.nodes[i]);if(!a||!b)continue;nodes.set(a.id,a);nodes.set(b.id,b);const distance=haversine(a,b),key=a.id<b.id?`${a.id}-${b.id}`:`${b.id}-${a.id}`,mid={lat:(a.lat+b.lat)/2,lon:(a.lon+b.lon)/2},cy=Math.floor(mid.lat/cell),cx=Math.floor(mid.lon/cell);let near=[];for(let y=cy-1;y<=cy+1;y++)for(let x=cx-1;x<=cx+1;x++)near.push(...(crossGrid.get(`${y},${x}`)||[]));const crossingIds=near.filter(c=>haversine(mid,c)<35).map(c=>c.id);let green=false,water=false;for(const area of indexedAreas){const pad=.0005;if(mid.lat<area.minLat-pad||mid.lat>area.maxLat+pad||mid.lon<area.minLon-pad||mid.lon>area.maxLon+pad)continue;if(featureNear(mid,area.points,area.kind==='water'?45:25,area.polygon)){if(area.kind==='water')water=true;else green=true;}}const tags=way.tags||{},climb=Number.isFinite(a.ele)&&Number.isFinite(b.ele)?Math.abs(a.ele-b.ele):0,meta={distance,key,nearCross:crossingIds.length>0,crossingIds,green,water,climb,highway:tags.highway,surface:tags.surface||'',sidewalk:tags.sidewalk||''};add(a,b,meta);add(b,a,meta);}
  return{nodes,adj};
}

const nearestNode=(g,p)=>{let best=null,bd=Infinity;for(const n of g.nodes.values()){const d=haversine(p,n);if(d<bd){bd=d;best=n;}}return best;};
const edgeCost=(e,preset,reused)=>{let f=1;if(e.highway==='secondary')f*=e.sidewalk&&e.sidewalk!=='no'?1.55:2.8;else if(e.highway==='tertiary')f*=e.sidewalk&&e.sidewalk!=='no'?1.15:1.5;else if(e.highway==='service')f*=1.12;else if(e.highway==='steps')f*=1.65;if(['footway','path','pedestrian','living_street'].includes(e.highway))f*=.88;if(['cobblestone','sett'].includes(e.surface))f*=1.2;if(e.nearCross)f*=preset==='nostops'?10:1.12;if(preset==='nature'){if(e.green)f*=.36;if(['path','footway'].includes(e.highway))f*=.74;}if(preset==='scenic'){if(e.green)f*=.5;if(e.water)f*=.42;if(e.climb>1)f*=.86;if(['path','footway'].includes(e.highway))f*=.82;}if(preset==='balanced'&&e.green)f*=.88;if(reused)f*=12;return Math.max(e.distance*.2,e.distance*f);};
class MinHeap{constructor(){this.a=[];}get size(){return this.a.length;}push(x){let i=this.a.push(x)-1;while(i){let p=(i-1)>>1;if(this.a[p][0]<=x[0])break;this.a[i]=this.a[p];i=p;}this.a[i]=x;}pop(){const root=this.a[0],last=this.a.pop();if(this.a.length){let i=0;this.a[0]=last;while(true){let l=i*2+1,r=l+1,s=i;if(l<this.a.length&&this.a[l][0]<this.a[s][0])s=l;if(r<this.a.length&&this.a[r][0]<this.a[s][0])s=r;if(s===i)break;[this.a[i],this.a[s]]=[this.a[s],this.a[i]];i=s;}}return root;}}
function dijkstra(g,start,goal,preset,used){const dist=new Map([[start,0]]),prev=new Map(),heap=new MinHeap();heap.push([0,start]);while(heap.size){const[cost,id]=heap.pop();if(cost!==dist.get(id))continue;if(id===goal)break;for(const e of g.adj.get(id)||[]){const nc=cost+edgeCost(e,preset,used.has(e.key));if(nc<(dist.get(e.to)??Infinity)){dist.set(e.to,nc);prev.set(e.to,{id,edge:e});heap.push([nc,e.to]);}}}if(!prev.has(goal))return null;const ids=[goal],edges=[];let cur=goal,actual=0;while(cur!==start){const p=prev.get(cur);if(!p)return null;actual+=p.edge.distance;edges.push(p.edge);cur=p.id;ids.push(cur);}return{ids:ids.reverse(),distance:actual,edges:edges.reverse()};}
function candidate(g,origin,start,target,radius,rotation,preset){const points=[start];for(let i=0;i<4;i++)points.push(nearestNode(g,destination(origin,radius,rotation+i*90)));points.push(start);const used=new Set(),ids=[],edges=[];let total=0,repeatedMeters=0;for(let i=1;i<points.length;i++){if(!points[i-1]||!points[i]||points[i-1].id===points[i].id)continue;const path=dijkstra(g,points[i-1].id,points[i].id,preset,used);if(!path)return null;if(ids.length)path.ids.shift();ids.push(...path.ids);total+=path.distance;for(const e of path.edges){if(used.has(e.key))repeatedMeters+=e.distance;used.add(e.key);edges.push(e);}}if(ids.length<3||!total)return null;const greenMeters=edges.reduce((s,e)=>s+(e.green?e.distance:0),0),waterMeters=edges.reduce((s,e)=>s+(e.water?e.distance:0),0),crossings=new Set(edges.flatMap(e=>e.crossingIds||[])).size,error=Math.abs(total-target)/target,repeat=repeatedMeters/total,green=greenMeters/total,water=waterMeters/total,crossingsPerKm=crossings/(total/1000);let score=error*6+Math.max(0,error-.15)*25+repeat*5;if(preset==='balanced')score-=green*.25;if(preset==='nature')score-=green*2.4;if(preset==='scenic')score-=green*1.7+water*2;if(preset==='nostops')score+=crossingsPerKm*.14;return{coordinates:ids.map(id=>[g.nodes.get(id).lat,g.nodes.get(id).lon]),distanceMeters:total,score,stats:{greenMeters,waterMeters,crossings,repeatedMeters}};}

export function findLoop(graph,origin,target,preset,onCandidate){const start=nearestNode(graph,origin);if(!start)return null;let radius=target/(2*Math.PI),best=null;for(let attempt=0;attempt<3;attempt++){let ringBest=null;for(const rotation of[0,22,44,66,88,110,132,154]){const c=candidate(graph,origin,start,target,radius,rotation+attempt*7,preset);if(c&&(!ringBest||c.score<ringBest.score))ringBest=c;if(c&&(!best||c.score<best.score)){best=c;onCandidate?.(c);}}if(ringBest){const error=Math.abs(ringBest.distanceMeters-target)/target,repeat=ringBest.stats.repeatedMeters/ringBest.distanceMeters;if(error<=.1&&repeat<=.14)break;radius*=Math.max(.7,Math.min(1.38,target/ringBest.distanceMeters));}else radius*=.78;}return best;}

const edgeStats=(edges,repeatedMeters=0)=>({greenMeters:edges.reduce((s,e)=>s+(e.green?e.distance:0),0),waterMeters:edges.reduce((s,e)=>s+(e.water?e.distance:0),0),crossings:new Set(edges.flatMap(e=>e.crossingIds||[])).size,repeatedMeters});
const pathCoordinates=(graph,ids)=>ids.map(id=>[graph.nodes.get(id).lat,graph.nodes.get(id).lon]);
const bearingsFor=direction=>({north:[315,0,45],east:[45,90,135],south:[135,180,225],west:[225,270,315]}[direction]||[0,45,90,135,180,225,270,315]);

export function findOneWay(graph,origin,target,preset,direction='auto',onCandidate){
  const start=nearestNode(graph,origin);if(!start)return null;let best=null;
  for(let attempt=0;attempt<3;attempt++){const radius=target*(.72+attempt*.14);for(const bearing of bearingsFor(direction)){const end=nearestNode(graph,destination(origin,radius,bearing));if(!end||end.id===start.id)continue;const path=dijkstra(graph,start.id,end.id,preset,new Set());if(!path)continue;const error=Math.abs(path.distance-target)/target,stats=edgeStats(path.edges),green=stats.greenMeters/path.distance,water=stats.waterMeters/path.distance;let score=error*8+Math.max(0,error-.15)*25;if(preset==='nature')score-=green*1.5;if(preset==='scenic')score-=green+water*1.5;if(preset==='nostops')score+=stats.crossings/(path.distance/1000)*.1;const route={coordinates:pathCoordinates(graph,path.ids),distanceMeters:path.distance,score,stats};if(!best||score<best.score){best=route;onCandidate?.(route);}}}
  return best;
}

export function findOutAndBack(graph,origin,target,preset,direction='auto',onCandidate){
  const wrap=outward=>onCandidate?.({coordinates:outward.coordinates.concat(outward.coordinates.slice(0,-1).reverse()),distanceMeters:outward.distanceMeters*2,score:outward.score,stats:{greenMeters:outward.stats.greenMeters*2,waterMeters:outward.stats.waterMeters*2,crossings:outward.stats.crossings,repeatedMeters:outward.distanceMeters}}),outward=findOneWay(graph,origin,target/2,preset,direction,wrap);if(!outward)return null;return{coordinates:outward.coordinates.concat(outward.coordinates.slice(0,-1).reverse()),distanceMeters:outward.distanceMeters*2,score:outward.score,stats:{greenMeters:outward.stats.greenMeters*2,waterMeters:outward.stats.waterMeters*2,crossings:outward.stats.crossings,repeatedMeters:outward.distanceMeters}};
}

export function findParkLaps(graph,origin,target,preset,returnToStart=true,onCandidate){
  const start=nearestNode(graph,origin);if(!start)return null;const greenNodes=[];
  for(const[id,edges]of graph.adj)if(edges.some(e=>e.green))greenNodes.push(graph.nodes.get(id));
  greenNodes.sort((a,b)=>haversine(origin,a)-haversine(origin,b));const parkCandidates=[];for(const node of greenNodes)if(parkCandidates.every(other=>haversine(node,other)>250)){parkCandidates.push(node);if(parkCandidates.length===6)break;}let best=null;
  for(const parkNode of parkCandidates){const connector=dijkstra(graph,start.id,parkNode.id,preset,new Set());if(!connector)continue;const connectorTotal=connector.distance*(returnToStart?2:1),lapTarget=target-connectorTotal;if(lapTarget<350)continue;const lap=findLoop(graph,parkNode,lapTarget,'nature');if(!lap)continue;const connectorCoords=pathCoordinates(graph,connector.ids),coords=connectorCoords.concat(lap.coordinates.slice(1));if(returnToStart)coords.push(...connectorCoords.slice(0,-1).reverse());const distanceMeters=connectorTotal+lap.distanceMeters,connectorStats=edgeStats(connector.edges,returnToStart?connector.distance:0),stats={greenMeters:connectorStats.greenMeters*(returnToStart?2:1)+lap.stats.greenMeters,waterMeters:connectorStats.waterMeters*(returnToStart?2:1)+lap.stats.waterMeters,crossings:connectorStats.crossings+lap.stats.crossings,repeatedMeters:connectorStats.repeatedMeters+lap.stats.repeatedMeters},error=Math.abs(distanceMeters-target)/target,green=stats.greenMeters/distanceMeters,score=error*8+Math.max(0,error-.15)*25-green*2;const route={coordinates:coords,distanceMeters,score,stats};if(!best||score<best.score){best=route;onCandidate?.(route);}}
  return best;
}

export function findRoute(graph,origin,target,preset,{shape='loop',direction='auto',returnToStart=true,onCandidate}={}){if(shape==='oneway')return findOneWay(graph,origin,target,preset,direction,onCandidate);if(shape==='outback')return findOutAndBack(graph,origin,target,preset,direction,onCandidate);if(shape==='park')return findParkLaps(graph,origin,target,preset,returnToStart,onCandidate);return findLoop(graph,origin,target,preset,onCandidate);}

export function bboxFor(origin,target,shape='loop'){const reach=shape==='oneway'?target*.8:shape==='outback'?target*.44:target/(2*Math.PI)*1.12,radius=Math.max(700,reach),dLat=radius/111320,dLon=radius/(111320*Math.max(.2,Math.cos(origin.lat*Math.PI/180))),q=value=>Number(value.toFixed(3));return{s:q(origin.lat-dLat),w:q(origin.lon-dLon),n:q(origin.lat+dLat),e:q(origin.lon+dLon)};}
