import{M_PER_MI,bboxFor,buildGraph,findRoute}from'./routing.js';
import{loadMapData}from'./overpass.js';
const PRESETS=new Set(['balanced','nature','nostops','scenic']);
const SHAPES=new Set(['loop','outback','oneway','park']),DIRECTIONS=new Set(['auto','north','east','south','west']);

export async function createRoute(input,dependencies={loadMapData}){
  const loader=dependencies.loadMapData||loadMapData,onProgress=typeof dependencies.onProgress==='function'?dependencies.onProgress:()=>{},emit=(stage,data={})=>{try{onProgress({stage,...data});}catch{}};
  const latitude=Number(input?.latitude),longitude=Number(input?.longitude),distanceMiles=Number(input?.distanceMiles),preset=String(input?.preset||'balanced'),shape=String(input?.shape||'loop'),direction=String(input?.direction||'auto'),returnToStart=input?.returnToStart!==false;
  if(!Number.isFinite(latitude)||latitude<-90||latitude>90||!Number.isFinite(longitude)||longitude<-180||longitude>180)throw Object.assign(new Error('Valid latitude and longitude are required.'),{status:400,code:'INVALID_LOCATION'});
  if(!Number.isFinite(distanceMiles)||distanceMiles<.5||distanceMiles>20)throw Object.assign(new Error('Distance must be between 0.5 and 20 miles.'),{status:400,code:'INVALID_DISTANCE'});
  if(!PRESETS.has(preset))throw Object.assign(new Error('Unknown route preset.'),{status:400,code:'INVALID_PRESET'});
  if(!SHAPES.has(shape))throw Object.assign(new Error('Unknown route shape.'),{status:400,code:'INVALID_SHAPE'});
  if(!DIRECTIONS.has(direction))throw Object.assign(new Error('Unknown route direction.'),{status:400,code:'INVALID_DIRECTION'});
  const started=performance.now(),origin={lat:latitude,lon:longitude},target=distanceMiles*M_PER_MI,mapStart=performance.now();emit('loading-map');let mapData;try{mapData=await loader(bboxFor(origin,target,shape),{requireFeatures:preset==='nature'||preset==='scenic'||shape==='park'});}catch(error){if(!error.code)error.code='MAP_UNAVAILABLE';if(error.code==='FEATURE_DATA_UNAVAILABLE')error.message='Park and nature data is temporarily unavailable. Please try again.';throw error;}const graphStart=performance.now();emit('building-network',{elements:mapData.elements.length});const graph=buildGraph(mapData.elements),routeStart=performance.now();emit('network-ready',{nodes:graph.nodes.size});
  if(graph.nodes.size<10)throw Object.assign(new Error('Not enough runnable paths were found near this location.'),{status:422,code:'INSUFFICIENT_MAP_DATA'});
  const candidates=[],candidatePayload=route=>({coordinates:route.coordinates,distanceMiles:Number((route.distanceMeters/M_PER_MI).toFixed(2)),stats:{greenPercent:Math.round(route.stats.greenMeters/route.distanceMeters*100),crossings:route.stats.crossings,repeatedPercent:Math.round(route.stats.repeatedMeters/route.distanceMeters*100)},score:route.score});
  const route=findRoute(graph,origin,target,preset,{shape,direction,returnToStart,onCandidate:candidate=>{const payload=candidatePayload(candidate);candidates.push(payload);emit('candidate',{candidate:payload,index:candidates.length});}});if(!route)throw Object.assign(new Error(shape==='park'?'No suitable park circuit was found within this distance.':'No connected route could be built here.'),{status:422,code:'NO_ROUTE_FOUND'});
  const actual=route.distanceMeters/M_PER_MI;
  const result={distanceMiles:Number(actual.toFixed(2)),coordinates:route.coordinates,stats:{greenPercent:Math.round(route.stats.greenMeters/route.distanceMeters*100),crossings:route.stats.crossings,repeatedPercent:Math.round(route.stats.repeatedMeters/route.distanceMeters*100)},alternatives:candidates.slice(-3).reverse(),meta:{shape,direction,returnsToStart:shape==='loop'||shape==='outback'||(shape==='park'&&returnToStart),targetErrorPercent:Math.round(Math.abs(actual-distanceMiles)/distanceMiles*100),mapSource:mapData.source||'provided data',nodes:graph.nodes.size,timingsMs:{map:Math.round(graphStart-mapStart),graph:Math.round(routeStart-graphStart),routing:Math.round(performance.now()-routeStart),total:Math.round(performance.now()-started)}}};emit('complete',{result});return result;
}
